version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"